login/urls.py
from django.urls import path
from .import views as login_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Admin password reset.
    path('login/',auth_views.LoginView.as_view(template_name='login/login.html'),name='main-login'),#login/
    path('home_user/',login_views.home_user,name='home_user'),#'home_user/
    path('profile/',login_views.profile,name='profile'),
    path('register/',login_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='login/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='login/logout.html'),name='logout'),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='login/change-password.html',
            success_url = '/'
        ),
        name='change_password'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='login/password_reset.html'),name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='login/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='login/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='login/password_reset_complete.html'),name='password_reset_complete'),
    path('email_us/', login_views.emailUs, name='emailus'),
    path('about_us/', login_views.abouthabayeiki, name='aboutus'),
    path('delete/<int:pk>/',login_views.deleteuser,name='deleteuser'),
    path('activate/<uidb64>/<token>/',login_views.ActivateAccount.as_view(),name='activate'),

    
]

rwandabus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    
    path('',include('login.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('web.urls')),
    path('', include('booking.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('comment/', include('comment.urls')),
    path('api/', include('comment.api.urls')),
    path('activity/', include('actstream.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
#from django.conf.urls import url
from django.urls import path
from .import views

app_name = 'web'
urlpatterns = [
    #path('', views.find_bus, name='home'), 
    #url(r'^select/', views.select, name='select'),
    path('findbus/',views.find_bus, name='findbus'),
    path('select/',views.select, name='select'),
    path('allt/',views.alltickets, name='all-tickets'),
    path('company/', views.CompanyListView, name='company-home'),
    path('company/<str:order_by>', views.CompanyListView, name='company-home'),
    path('company/<int:pk>/', views.UserCompanyBusListView, name='company-detail'),
    path('company/dashboard/', views.company_dashboard, name='company-dashboard'),
 	#path('user/dashboard/<str:username>', UserDashboard.as_view(), name='user-dashboard'),
 	path('company/add/',views.company_create, name='company-create'),
    path('<int:pk>/update_company/', views.company_update, name='company-update'),
    path('<int:pk>/delete_company/', views.CompanyDeleteView, name='company-delete'),

    path('bus/add/',views.bus_create, name='bus-create'),
    path('bus/<int:pk>/<str:slug>/',views.company_bus_detail, name='company-bus-detail'),
    path('<int:pk>/update_bus/', views.bus_update, name='bus-update'),
    path('<int:pk>/delete_bus/', views.BusDeleteView, name='bus-delete'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from datetime import datetime
# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	email_confirmed = models.BooleanField(default=False)
	user_image = models.ImageField(default='prophile_photo/user_profile.png',upload_to="prophile_photo")
	birth_date = models.DateTimeField(null=True, blank=True)

	sex = models.CharField(choices=(
		('M',"Male"),
		('F',"Female")), 
	max_length= 1,default='')

	status = models.CharField(choices=(
		('S','Single'),
		('M','Married'),
		('D','Divoreced'),
		('Se','Separated')), 
		max_length=20, default='')


	def __str__(self):
		return f'{self.user.username} Profile'



		def save(self,*args, **kwargs):
			super().save()
			img = Image.open(self.image.path)
			if img.height > 300 or img.width>300:
				output_size = (300,300)
				img.thumbnail(output_size)
				img.save(self.image.path)

login/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile
from django.contrib.admin import widgets

class UserRegForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields=['username','email','password1','password2']


#class DateInput(forms.DateInput):
    #input_type ='date'
        
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    #Birth_date = forms.DateField(widget=DateInput)
    #Birth_date = forms.DateTimeField(input_formats=['%d/%m/%Y'])
    class Meta:
        model = User
        fields =['username','email','first_name','last_name']
        

        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        #birth_date = forms.DateField(widget=DateInput)
        model = Profile
        fields = ['sex','status','birth_date','user_image']
        
        widgets = {
        'birth_date': forms.DateInput(format='%d/%m/%Y'),
    }

class ContactForm(forms.Form):
    #email = forms.EmailField(required=True)
    enter_your_email = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = User
        fields =['username','email']

login/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegForm,UserUpdateForm,ProfileUpdateForm, ContactForm
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic 
from django.contrib.auth.models import User

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib.auth import login, authenticate
#from django.utils.encoding import force_bytes, force_str
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from .tokens import account_activation_token
from django.views.generic import View
from web.models import Bus
from booking.models import  LineItem



# Create your views here.
def register(request):
    if request.method== 'POST':
        form = UserRegForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your rwandabus account.'
            message = render_to_string('login/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
                })
            to_email = form.cleaned_data.get('email')
            #email = EmailMessage(mail_subject, message, to=[to_email])
            #email.send()
            user.email_user(mail_subject, message)
            #return HttpResponse('Please confirm your email addressto complete the registration')
            messages.success(request,f'Please confirm your email address to complete the registration')
            return redirect('login')

            #username = form.cleaned_data.get('username')
            #messages.success(request,f'User {username} created successfully!You can login')
            #return redirect('login')
    else:
        form = UserRegForm()
    return render(request,'login/register.html',{'form':form})




class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.profile.email_confirmed = True
            user.save()
            login(request, user)
            messages.success(request, ('Your account have been confirmed.'))
            return redirect('login')
        else:
            messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
            return redirect('login')



#@login_required
#def home_user(request):
    #return render(request, 'login/home_user.html')


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance = request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.profile)
        
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your Profile has been update Successfully!!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance = request.user)
        p_form = ProfileUpdateForm(instance = request.user.profile)
    
    context ={"u_form":u_form,"p_form":p_form,}
    return render(request,'login/profile.html',context)




def emailUs(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            enter_your_email = form.cleaned_data['enter_your_email']
            email = form.cleaned_data.get('email')
            #email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            try:
                send_mail(enter_your_email, message, email, ['infoitike@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            username = form.cleaned_data.get('username')
            messages.success(request,f' Message sent successfully!')
            return redirect('emailus')
    return render(request, "login/contact_us.html", {'form': form})


def abouthabayeiki(request):
    return render(request, 'login/about_us.html')






#@login_required
#class DetailsView(generic.DetailView):
    #model = Ourservices

@login_required
def deleteuser(request,pk):
    if request.method == 'POST':
        try:
            u = User.objects.get(id=pk)
            #u.delete()
            u.is_active = False
            u.save()
            messages.success(request,f'User  successfully deactivated!') 
            return redirect('mainhome')
        except User.DoesNotExist:
            messages.error(request,f'User does not exist.')
            return render(request,'login/confirmdelete.html')
    else:
        return render(request,'login/confirmdelete.html')
    



@login_required
def home_user(request):
    os = LineItem.objects.filter(user=request.user ).order_by('-id')
    page = request.GET.get('page', 1)

    paginator = Paginator(os, 5)
    try:
        os = paginator.page(page)
    except PageNotAnInteger:
        os = paginator.page(1)
    except EmptyPage:
        os = paginator.page(paginator.num_pages)
    return render(request, "login/home_user.html", {'os': os,})

login/templates/login/about_us.html
{% extends "login/base.html" %}
{% load static %}
{% block content %}
<p class="text-primary text-center h3"> <img src="{% static 'wjh.png' %}" alt="Mylogo" width="50" height="50" class="rounded-circle m-1">iTiKe</p>
<div class="line"></div> 
<p class="text-danger text-center"><i><b> iTiKe | Online Transport Ticketing<b></i></p>
 <div class="line"></div>       
<p class="text-dark"> iTiKe | Online Transport Ticketing is a platform that provides portal for users to access  Online Transport ticketing,News, Advert Business & Tenders, and Chat. We believe in  connecting people to real business, best products and services.
</p>
<div class="line"></div>
<p class="text-info"> ITIKE | Online Transport Ticketing ni urubuga rutanga portal ku abantu kugirango bagure amatike ya Bus na Taxi, Guhaha hakoreshejwe mudasobwa, Kwamamaza Ubucuruzi & Amasoko, hamwe no Kuganira hakoreshejwe ikoranabuhanga. Twizera guhuza abantu na business zizewe, ibicuruzwa na serivisi nziza.</p>
<div class="line"></div>
<p>
        

{% endblock content %}

login/templates/login/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

login/templates/login/base.html
<!DOCTYPE html>
<html>
<head>
{% load static %}

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}iTiKe{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'style4.css' %}">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">


     <script src="{% url 'js-catlog' %}"></script>
     <script src="{% static '/admin/js/core.js' %}"></script>
     <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">



</head>
 <body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <a href="{% url 'index' %}">

                <text class="h4"><i class="fas fa-bus m-1"></i>iTiKe</text>
                
            </a>
            </div>

            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-bus"></i>
                        Bus|Tickets
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'web:findbus' %}">Bus|Route</a>
                        </li>
                        <li>
                            <a href="{% url 'index1' %}">Bus|Company</a>
                        </li>
                        <li>
                            <a href="{% url 'web:all-tickets' %}">Tickets</a>
                        </li>
                        {%if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_cart' %}"><i class="fas fa-shopping-cart" aria-hidden="true"></i>{{ cart_item_count }}</a>
                        </li>
                        <li>
                            <a href="{% url 'home_user'%}">orders</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'register' %}">Register</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
                <li>
                    <a href="{% url 'aboutus' %}">
                        <i class="fas fa-briefcase"></i>
                        About Us
                    </a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-toolbox"></i>
                        Tools
                    </a>
                    {% if user.is_authenticated %}
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{% url 'web:company-create' %}">Register Company</a>
                        </li>
                        
                        <li>
                            
                            <a href="{% url 'web:company-dashboard' %}">Dashboard</a>
                            
                        </li>
                        <li>
                            <a href="{% url 'web:company-home' %}">Companies</a>
                        </li>
                        
                        
                    </ul>
                    {% endif %}
                </li>
                <li>
                    <a href="{% url 'index' %}">
                        <i class="fas fa-home"></i>
                        Home
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-question"></i>
                        FAQ
                    </a>
                </li>
                <li>
                    <a href="{% url 'emailus' %}">
                        <i class="fas fa-paper-plane"></i>
                        Contact
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'logout' %}" method="post" style="display: inline;">
                        {% csrf_token %} {# This is ESSENTIAL for security! #}
                        <button type="submit" style="background: none; border: none; padding: 0; cursor: pointer; color: inherit; font: inherit;">
                            <i class="fas fa-sign-out-alt"></i>Logout
                        </button>
                    </form>
                </li>
                {% endif %}
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>iTiKe</span>
                    </button>
                    <a href="{% url 'index' %}">
                    <img src="{% static 'wjh.png' %}" alt="Mylogo" width="40" height="40" class="rounded-circle ml-1"><text class="text-primary font-weight-bold ">iTiKe</text><i class="fas fa-home ml-3"></i>
                    </a>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item">
                                
                                {% load tz %}

                                  {{ value|timezone:"Europe/Paris" }}

                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'web:findbus' %}"><text class="text-danger"><i class="fas fa-cog fa-spin"></i>Bus|Routes</text></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'index1' %}"><text class="text-dark"><i class="fas fa-bus"></i>Bus|Company</text></a>
                            </li>
                            {%if user.is_authenticated %}
                            
                            <li class="nav-item active">
                                <a class="nav-link text-danger" href="{% url 'show_cart' %}"><i class="fas fa-shopping-cart" aria-hidden="true"></i>{{ cart_item_count }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" href="{% url 'home_user' %}"> Orders</a>
                            </li>
                            <li class="nav-item"> 
                                <a class="nav-link text-primary" href="{% url 'profile' %}"><small class="text-dark">{{user.username}}</small><img class="rounded-circle account-img" height="40" width="40" src="{{user.profile.user_image.url}}"></a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}"><text class="text-primary"><i class="fas fa-user"></i>Register</text></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}"><text class="text-primary"><i class="fas fa-sign-in-alt"></i>Login</text></a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

      {% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}}">
{{message}}
</div>
{% endfor %}
{% endif %}
<div class="container-fluid">  
{% block content %}
{% endblock content %}

<div class="line"></div>
<p class="text-center text-primary small "><i class="fas fa-envelope mx-1"></i>infoitike@gmail.com</p>
<p class="text-center text-primary small"><i class="fas fa-phone mx-1"></i>+250 785540835 <i class="fas fa-map-marker mx-1"></i> Kigali - Rwanda</p>
     <p class="text-center text-dark small">&copy; Copyright 2025 - iTiKe.  All Rights Reserved.</p>
  <p>
    </div>
    </div>
 </div>
    

<!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>

</html>
  
  

  

login/templates/login/change-password.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Change Password Page{% endblock title %}

{% block content %} 
<p>
<h4 class="display">Change Password</h4></p>
<div class="line"></div>
<p>
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-outline-danger btn-block"><i class="icon-lock4"></i>Submit</button>
    </form>
</p>
<div class="line"></div>
    <p >
    	<a href="{% url 'profile' %}">Click Here to Cancel</a>
    </p>
{% endblock content %}

login/templates/login/confirmdelete.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<p>
   <h4>Delete user : {{ user.username }}?</h4> <img class="img-circle account-img m-3" height="100" width="100" src="{{user.profile.user_image.url}}">
 </p>
 <div class="line"></div>
 <p>
<form method="POST" action="">
{% csrf_token %}
Are you sure you want to delete: {{ user.username }}? 
<button type="submit" class="btn btn-outline-danger " value="Yes">Yes</button>
<a class="btn btn-outline-info mx-3" href="{% url 'profile' %}"> Cancel </a>
</form>
</p>
{% endblock content %}

login/templates/login/home_user.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% load static %}



{% block content %}
<p class="text-info">
{{user.username}} ' Tickets orders:
 {% if os %}
 {% for o in os %}

<p class="text-dark small"> {{ forloop.counter }}-{{o.date_added}}- {{o.order.name}} -Frw{{o.price}}-Qty:{{o.quantity}}-{{ o.bus.bus_company.name}}-{{ o.bus.location_from}}->{{ o.bus.location_to}}</p>
 {% endfor %}


 {% else %}
 <p class="text-danger text-center"> You did not order yet</p>
 {% endif %}
</p>

<div class="row justify-content-center border bg-light">
         <div class="pagination">
    <span class="step-links">
        {% if os.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ buss.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            <small class="text-info">Page {{ os.number }} of {{ os.paginator.num_pages }}.</small>
        </span>

        {% if os.has_next %}
            <a href="?page={{ buss.next_page_number }}">next</a>
            <a href="?page={{ buss.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock content %}

login/templates/login/login.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
 <p>
    <text class="text-primary"><i class="fab fa-facebook-square" aria-hidden="true"></i>
             <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook
             </a></text></p>

<p>
    <text class="text-danger"><i class="fab fa-twitter-square" aria-hidden="true"></i>
             <a href="#">Login with twitter
             </a></text>
</p>
<p>
         <div class="line"></div>

               <form method="POST">
               {% csrf_token %}
                 {{form | crispy }}
                <button class="btn btn-outline-danger" value="submit">Sign In</button>
                </form>
            </p>
<div class="line"></div>
<p>       
<form role="form">
<small class="text-danger m-3 p-3">New User? </small><i class="fas fa-user"> </i> <a href="{% url 'register' %}">Sign Up Here</a>
</form>
</p>
<div class="line"></div>
<p>
<small class="text-danger m-3 p-3">Forgot Your Password? </small><a href="{% url 'password-reset' %}">Click Here to Reset Password</a>
</p>
{% endblock content %}

login/templates/login/logout.html
{% extends 'login/base.html' %}
{% block content %}
<p class="display-5">You are logged out!</p>
<div class="line"></div>
<p class="text-danger "><i class="fas fa-user"></i><a href="{% url 'login' %}">Click here to
login again</a></p>
<div class="line"></div>
<p class="text-danger"><i class="fas fa-home"></i><a href="{% url 'index' %}">Go to Home
page</a></p>
{% endblock content %}

login/templates/login/password_reset_complete.html
{% extends 'login/base.html' %}
{% block content %}
<p>

<h3>Your password has been reset! You can <a href="{% url 'login'%}">Login Here</a></h3>
</p>
{% endblock content %}

login/templates/login/password_reset_confirm.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<p class="text-danger text-center h6"> Reset Password</p>
<p>Enter your new password</p>
<div class="line"></div>
<p>
<form class="form" action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form | crispy }}
<button type="submit" class="btn btn-primary btn-lg btn-block"><i class="icon-lock4"></i> Change Password</button>
</form> 
</p>                   
{% endblock %}

login/templates/login/password_reset_done.html
{% extends 'login/base.html' %}
{% block content %}
<p class="text-danger text-center h6">
An email has been sent with instructions to reset the password!!
</p>
{% endblock content %}

login/templates/login/register.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<p><h3>Sign Up</h3></p>
<div class="line"></div>

<p>
<form method="POST">
{% csrf_token %}
{{form | crispy}}
<button class="btn btn-outline-danger" value="submit">Sign Up</button>
</form>
</p>

<div class="line"></div>
<p class="text-danger">Have an account? <a href="{% url 'login' %}"><i class="fas fa-user m-2"></i> Login Here</a></p>
{% endblock content %}