rwandabus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    
    path('',include('login.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('web.urls')),
    path('', include('booking.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('comment/', include('comment.urls')),
    path('api/', include('comment.api.urls')),
    path('activity/', include('actstream.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web/urls.py
#from django.conf.urls import url
from django.urls import path
from .import views

app_name = 'web'
urlpatterns = [
    #path('', views.find_bus, name='home'), 
    #url(r'^select/', views.select, name='select'),
    path('findbus/',views.find_bus, name='findbus'),
    path('select/',views.select, name='select'),
    path('allt/',views.alltickets, name='all-tickets'),
    path('company/', views.CompanyListView, name='company-home'),
    path('company/<str:order_by>', views.CompanyListView, name='company-home'),
    path('company/<int:pk>/', views.UserCompanyBusListView, name='company-detail'),
    path('company/dashboard/', views.company_dashboard, name='company-dashboard'),
 	#path('user/dashboard/<str:username>', UserDashboard.as_view(), name='user-dashboard'),
 	path('company/add/',views.company_create, name='company-create'),
    path('<int:pk>/update_company/', views.company_update, name='company-update'),
    path('<int:pk>/delete_company/', views.CompanyDeleteView, name='company-delete'),

    path('bus/add/',views.bus_create, name='bus-create'),
    path('bus/<int:pk>/<str:slug>/',views.company_bus_detail, name='company-bus-detail'),
    path('<int:pk>/update_bus/', views.bus_update, name='bus-update'),
    path('<int:pk>/delete_bus/', views.BusDeleteView, name='bus-delete'),
]

web/templates/alltickets.html
{% extends 'login/base.html' %}
{% load static %}
{% load crispy_forms_field %}
{% load hitcount_tags %}


{% block content %}
<p> 
	
            {% if buses %}

{% for bus in buses %}
<p class="text-center">
<div class="table-responsive">
<table class="table table-hover table-responsive">
  <thead class="thead-danger">
    <tr>
      <th scope="col">Bus Company</th>
      <th scope="col">Departure</th>
      <th scope="col">Arrival</th>
    </tr>
  </thead>
  <tbody class="table table-bordered">
    <tr>
      <th scope="row" class="h3"><a href="#">{{ bus.bus_company }}</th>
      <td><a href="#"><text class="text text-danger"><i class="fas fa-map-marker mx-1"></i>{{ bus.location_from }}</text></a></td>
      <td><a href="#"><i class="fas fa-map-marker mx-1"></i>{{ bus.location_to }}</a></td>  
    </tr>
    <tr>
      <td><a href="#"><i class="fa fa-bus" aria-hidden="true"></i>
{{ bus.type_of_bus }}<br><small>{{ bus.plate_number}}</small><br><span class="badge badge-pill badge-dark">{{ bus.seats }} <small> seats</small></span></td>
      <td><a href="#"><text class="text text-danger"><i class="fas fa-clock mx-1" aria-hidden="true"></i>
{{ bus.departure_time }}<br>{{ bus.departure_date }}</text></a></td>
      <td><a href="#"><text class="text text-info"><i class="fas fa-clock mx-1" aria-hidden="true "></i>
{{ bus.arrival_time }}<br>{{ bus.arrival_date }}</text></a></td>
    </tr>

    <th scope="col">Ratings</th>
      <th scope="col" colspan="2" class="text-center">Fare | Igiciro</th>
        <tr>

       <td >
<br><span class="badge badge-pill badge-primary">
  Views</span> <span class="badge badge-light">{% get_hit_count for bus %}</span>
<br>
<span class="badge badge-pill badge-danger">
<i class="fas fa-thumbs-up mx-2" aria-hidden="true"></i>{{ bus.liked.all.count }}</span>
</td>
<td ><span class="badge  badge-dark"><h5>Frw <text class="font-weight-bold">{{ bus.ticket_price }}</text></h5></span></td>
       

        <td><a href="{% url 'bus_detail' bus.pk bus.slug %}"><text class="text text-danger"><input class="btn btn-outline-danger float-right" type="submit" value="Book Ticket"></text></a></td>

 </tr>

    </table>
    <small class="text-primary">added {{ bus.created|timesince }} ago</small>
</p>
{% endfor %}
<p>
            {% else %}
            
                <h2>No <img src="{% static 'img/favicon.png' %}" > found.</h2> </p>
            {% endif %}

<div class="row justify-content-center border bg-light">
         <div class="pagination">
    <span class="step-links">
        {% if buses.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ buss.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            <small class="text-info">Page {{ buses.number }} of {{ buses.paginator.num_pages }}.</small>
        </span>

        {% if buses.has_next %}
            <a href="?page={{ buss.next_page_number }}">next</a>
            <a href="?page={{ buss.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
</p>
{% endblock content %}

web/templates/bus_confirm_delete.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<p>
<form method="POST" action="">
{% csrf_token %}
Are you sure you want to delete this vehicle. This can not be undone!!! 
<button type="submit" class="btn btn-outline-danger " value="Yes">Yes</button><br>
<a class="btn btn-outline-info mx-3" href="{% url 'web:company-home' %}"> Cancel </a>
</form>
</p>
{% endblock content %}

web/templates/bus_form.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load hitcount_tags %}
{% load comment_tags %}


{% block content %}
<p><a href="{% url 'web:company-home' %}" class="text-primary"><< Back</a></p>

<p>      
 {% if message %} <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ message }}</div> {% endif %}</p> 
 <p><text class="text-danger font-weight-bold">
 Company Name</text> :<text class="text-dark font-weight-bold">{{ user.company}}</text><br>
 <text class="text-danger font-weight-bold"> Manager :</text> <text class="text-dark font-weight-bold">{{user.username}}</text>
</p>
<div class="line"></div>
<p>
 <h5><text class="text-danger font-weight-bold">Add Bus | Vehicle</text></h5>
    *slug can be any name. E.g: your company name
</p>
<p>
        
                <form  method="post" form enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value="Register Bus | vehicle" class="btn btn-outline-danger m-4" >
                </form>
           </p>
{% endblock %}

web/templates/company_bus_detail.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load hitcount_tags %}
{% load comment_tags %}


{% block content %}
<p><a href="{% url 'web:company-home' %}" class="text-primary"><< Back</a></p>
<p>
<img src="{% if bus.image %}{{ bus.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="70" height="70" class="rounded-circle">
<text class="text-primary">Ticket price : {{ bus.ticket_price }}</text><br>
<text class="text-dark">PlateNumber :{{bus.plate_number}} </text><br>
<text class="text-dark">Company name :{{bus.bus_company}} </text><br>
</p>
<p>
<a href="{% url 'web:bus-update' bus.id %}"><text class="text-primary btn btn-outline-danger"><i class="fas fa-cog fa-fw"></i>Update | Modify</text></a></p>
<p><a href="{% url 'web:bus-delete' bus.id %}"><text class="text-dark"><i class="fas fa-skull"></i><i class="fas fa-trash-alt"></i> </text><text class="text-danger small">Remove | Delete This Car </text> </a></p>
<text class="text-info">Vehicle type :{{bus.type_of_bus}} </text><br>
<text class="text-danger">Departure date :{{bus.departure_date}} </text><br>
<text class="text-danger">Departure time :{{bus.departure_time}} </text><br>
<text class="text-primary">From :{{bus.location_from}} </text><br>
<text class="text-primary">To :{{bus.location_to}} </text><br>
<text class="text-dark">Number of seats :{{bus.seats}} </text><br>
</p>
<p class="card-text border bg-light"> <text class="text-primary">{% get_hit_count for bus %} views</text> <text class="text-danger font-weight-bold float-right">{{ bus.liked.all.count }} Likes</text></p>
<p class="text-center text-danger">Booking History</p>
<p>
	{% if orders %}
	{% for order in orders %}
	<p class="small text-dark">{{forloop.counter}}-{{order.date_added}}-Frw{{order.price}}-Qty:{{order.quantity}}-User:{{order.user}}-Customer:{{order.order.name}}</p>
	
       {% endfor %}
	{% else %}
<p class="text-danger text-center ">No Booking Found</p>
	{% endif %}

</p>
<div class="line"></div>
<p>
  {% render_comments bus request %}
         {% include_static %}
</p>
{% endblock content %}

web/templates/company_confirm_delete.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<p>
<form method="POST" action="">
{% csrf_token %}
Are you sure you want to delete Your Company. This will delete all vehicles associated with your companies!!! 
<button type="submit" class="btn btn-outline-danger " value="Yes">Yes</button><br>
<a class="btn btn-outline-info mx-3" href="{% url 'web:company-home' %}"> Cancel </a>
</form>
</p>
{% endblock content %}

web/templates/company_dashboard.html
{% extends 'login/base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load comment_tags %}


{% block content %}
{% if message %} <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ message }}</div> {% endif %}</p> 


{% if co %}
{% for company in co %}
{% if company.available == True and company.manager == user %}
<p class="text-center text-danger h6">{{user.username}}, You Already registered Company: <text class="text-primary text-center h6"> {{ company.name }} </text></p>
<div class="line"></div>
	<p class="text-danger h4">{{company.name}} <img src="{% if company.logo %}{{ company.logo.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="30" height="30" class="rounded-circle m-1"></p>
<p>Phone:{{company.phone}} <br>
{{company.email}} <br>
{{company.description}}<br>
{{company.address}} </p>
<a href="{% url 'web:company-detail' company.id %}"><text class="btn btn-outline-danger text text-primary"><i class="fas fa-cog fa-fw"></i>Company Dashboard</text></a></p>

<p><small class="text-dark">Added {{ company.created|timesince }} ago</small></p>
<p>
 <text class="text-primary">{% get_hit_count for company %} views</text> <text class="text-danger font-weight-bold float-right">{{ company.cliked.all.count }} <i class="fa fa-thumbs-up" aria-hidden="true"></i></text></p>

 {% elif company.available == False and company.manager == user %}
<p class="text-center text-danger h6">You Already registered Company: <text class="text-primary text-center h6"> {{ company.name }} </text></p>
<p class="text-primary">{{ company.name }} is not avtive yet.  iTiKe will contact you after verification </p> 
{% endif %}
{% endfor %}

{% else %}
<p class="text-danger">{{ user.username }}, You Did Not Register a Company.</p>
<p class="text-primary"><a href="{% url 'web:company-create' %}">you Can Register a Company| Business Here.</a></p>
{% endif %}
{% endblock content %}

web/templates/company_detail.html
{% extends 'login/base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load comment_tags %}


{% block content %}
<p><a href="{% url 'web:company-home' %}" class="text-primary"><< Back</a></p>
	{% if company and company.available == True and company.manager == user %}
<p class="text-primary h6">{{company.name}}<img src="{% if company.logo %}{{ company.logo.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="50" height="50" class="rounded-circle m-2"><br></p>
<p>
Phone : {{company.phone}}<br>
{{company.email}}<br>
{{company.description}} <br>
{{company.address}} <br><p>
<p>
<a href="{% url 'web:company-update' company.id %}"><text class="text-primary btn btn-outline-danger"><i class="fas fa-cog fa-fw"></i>Update | Modify</text></a></p>
<p><a href="{% url 'web:bus-create' %}"><text class="text-primary btn btn-outline-danger"><i class="fas fa-bus"></i>Add New bus | vehicle</text> </a></p>
<p>
<p><a href="{% url 'web:company-delete' company.id %}"><text class="text-dark"><i class="fas fa-skull"></i><i class="fas fa-trash-alt"></i> </text><text class="text-danger small">Remove | Delete Your Company</text> </a></p>
<small class="text-rpimary">Added {{ company.created|timesince }} ago</small></p>
<p>
 <text class="text-primary">{% get_hit_count for company %} views</text> <text class="text-danger font-weight-bold float-right">{{ company.cliked.all.count }} <i class="fa fa-thumbs-up" aria-hidden="true"></i></text></p>
{% endif %}
<p class="text-danger text-center h6"> Vehicles in {{company.name}} </p>
{% if buses %}
{% for bus in buses %}
<p>
<img src="{% if bus.image %}{{ bus.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="50" height="50" class="rounded-circle">
  
         {{bus.bus_type}} 
        <small class="text-muted font-weight-bold">{{ bus.bus_company }} | {{ bus.plate_number}} </small><br>
        <small class="text-danger">Time :{{bus.departure_time}},{{bus.departure_date}} </small><br>
        <small class="text-primary">{{bus.location_from}} To {{bus.location_to}}</small><br>
        <small class="text-dark">Added {{ bus.created|timesince }} ago</small><br>
        <a href="{% url 'web:company-bus-detail' bus.pk bus.slug %}"><text class="text-primary btn btn-outline-danger"><i class="fas fa-bus" aria-hidden="true"></i>Vehicle detail</text></a></p>


{% endfor %}
{% else %}
<p><h2>No <img src="{% static 'img/favicon.png' %}" > found</h2> </p>
{% endif %}



<div class="row justify-content-center border bg-light">
         <div class="pagination">
    <span class="step-links">
        {% if buses.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ buss.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            <small class="text-info">Page {{ buses.number }} of {{ buses.paginator.num_pages }}.</small>
        </span>

        {% if buses.has_next %}
            <a href="?page={{ buss.next_page_number }}">next</a>
            <a href="?page={{ buss.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock content %}

web/templates/company_form.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

<p><a href="{% url 'web:company-home' %}" class="text-primary"><< Back</a></p>

{% block content %}
      
 {% if message %}<p>  <i class="fas fa-exclamation-triangle" aria-hidden="true"></i> {{ message }}</p> {% endif %} 
<div class="line"></div>

{% if exst %}
{% for c in exst %}
<p class="text-center text-danger h6"><a href="{% url 'web:company-home' %}">You already registered company:<text class="text-primary"> {{c.name}}</text></a></p>
{% endfor %}
{% else %}

<p><text class="text-danger font-weight-bold h6">Register company | Business</text>
                <form  method="post"  enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value="Create company" class="btn btn-outline-danger" >
                </form>
{% endif %}
</p>
{% endblock %}

web/templates/company_home.html
{% extends 'login/base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load comment_tags %}


{% block content %}
{% if message %} <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ message }}</div> {% endif %}</p> 

{% for company in companies %}

{% if company.available == True and company.manager == user %}
<p class="text-center text-danger h6">You Already registered Company: <text class="text-primary text-center h6"> {{ company.name }} </text></p>
<div class="line"></div>
	<p class="text-danger h4">{{company.name}} <img src="{% if company.logo %}{{ company.logo.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="30" height="30" class="rounded-circle m-1"></p>
<p>Phone:{{company.phone}} <br>
{{company.email}} <br>
{{company.description}}<br>
{{company.address}} </p>
<a href="{% url 'web:company-detail' company.id %}"><text class="text text-primary btn btn-outline-danger"><i class="fas fa-cog fa-fw"></i>Company Dashboard</text></a></p>

<p><small class="text-dark">Added {{ company.created|timesince }} ago</small></p>
<p>
 <text class="text-primary">{% get_hit_count for company %} views</text> <text class="text-danger font-weight-bold float-right">{{ company.cliked.all.count }} <i class="fa fa-thumbs-up" aria-hidden="true"></i></text></p>

 {% elif company.available == False and company.manager == user %}
<p class="text-center text-danger h6">You Already registered Company: <text class="text-primary text-center h6"> {{ company.name }} </text></p>
<p class="text-primary">{{ company.name }} is not avtive yet.  iTiKe will contact you after verification </p> 
{% endif %}
{% endfor %}

<div class="line"></div>

<p class="text-center text-danger h6">Other companies working with us</p>
	{% if companies %}
	{% for company in companies %}
	{% if company.available == True %}
<p class="text-primary h6">{{company.name}} <img src="{% if company.logo %}{{ company.logo.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="30" height="30" class="rounded-circle m-1"></p>
Phone:{{company.phone}}<br>
{{company.email}} <br>
{{company.description}} <br>
{{company.address}} </p>
<p><small class="text-primary">Added {{ company.created|timesince }} ago</small></p>
<p>
 <text class="text-primary">{% get_hit_count for company %} views</text> <text class="text-danger font-weight-bold float-right">{{ company.cliked.all.count }} <i class="fa fa-thumbs-up" aria-hidden="true"></i></text></p>
 <p>
          <form action="{% url 'like-company' %}" method="POST" class=" float-right">
          {% csrf_token %}

          <input type="hidden" name="bus_id" value="{{ company.id }}"> 
          {% if  user not in company.cliked.all %}
          <button class ="btn btn-outline-danger" type="submit">

          <i class="fa fa-thumbs-up" aria-hidden="true"></i>
           Like</button>

          {% else %}
          <button class="btn btn-outline-danger " type="submit"><i class="fa fa-thumbs-down" aria-hidden="true"></i>UnLike</button>

          {% endif %}

        </form>
        </p>
 <div class="line"></div>
{% endif %}
{% endfor %}
{% else %}
<p><h4> No Company Found </h4></p>
	{% endif %}


<div class="row justify-content-center border bg-light">
         <div class="pagination">
    <span class="step-links">
        {% if companies.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ buss.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            <small class="text-info">Page {{ companies.number }} of {{ companies.paginator.num_pages }}.</small>
        </span>

        {% if companies.has_next %}
            <a href="?page={{ buss.next_page_number }}">next</a>
            <a href="?page={{ buss.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock content %}

web/templates/company_update.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% load static %}



{% block content %}
<p><a href="{% url 'web:company-home' %}" class="text-primary"><< Back</a></p>
<p>       
 {% if message %} <i class="fas fa-exclamation-triangle" aria-hidden="true"></i> {{ message }} {% endif %} </p>
<div class="line"></div>
<p class="text-danger text-center font-weight-bold h6">Update 
                <form  method="post"  enctype='multipart/form-data'>
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value="Update" class="btn btn-outline-danger" >
                </form>
</p>

{% endblock %}

web/templates/home.html
{% extends "login/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

      {% if message %}
    {{ message }}

    {% endif %}
  {% block content %}
  <p>
    <form class="form-horizontal" action="{% url 'web:select' %}" method="GET" name="q" role="form">
        
    {{ form.media }}
    {{ form | crispy }}
        
    <input type="submit" value="Search" class="btn btn-outline-danger">
    
    </form>

  </p>
  {% endblock content %}

web/templates/select.html
{% extends 'login/base.html' %}
{% load static %}
{% load crispy_forms_field %}
{% load hitcount_tags %}

{% block content %}


   
            {% if buses %}

{% for bus in buses %}
<p class="text-center">
<div class="table-responsive">
<table class="table table-hover table-responsive">
  <thead class="thead-danger">
    <tr>
      <th scope="col">Bus Company</th>
      <th scope="col">Departure</th>
      <th scope="col">Arrival</th>
    </tr>
  </thead>
  <tbody class="table table-bordered">
    <tr>
      <th scope="row" class="h3"><a href="#">{{ bus.bus_company }}</th>
      <td><a href="#"><text class="text text-danger"><i class="fas fa-map-marker mx-1"></i>{{ bus.location_from }}</text></a></td>
      <td><a href="#"><i class="fas fa-map-marker mx-1"></i>{{ bus.location_to }}</a></td>  
    </tr>
    <tr>
      <td><a href="#"><i class="fa fa-bus" aria-hidden="true"></i>
{{ bus.type_of_bus }}<br><small>{{ bus.plate_number}}</small><br><span class="badge badge-pill badge-dark">{{ bus.seats }} <small> seats</small></span></td>
      <td><a href="#"><text class="text text-danger"><i class="fas fa-clock mx-1" aria-hidden="true"></i>
{{ bus.departure_time }}<br>{{ bus.departure_date }}</text></a></td>
      <td><a href="#"><text class="text text-info"><i class="fas fa-clock mx-1" aria-hidden="true "></i>
{{ bus.arrival_time }}<br>{{ bus.arrival_date }}</text></a></td>
    </tr>

    <th scope="col">Ratings</th>
      <th scope="col" colspan="2" class="text-center">Fare | Igiciro</th>
        <tr>

       <td >
<br><span class="badge badge-pill badge-primary">
  Views</span> <span class="badge badge-light">{% get_hit_count for bus %}</span>
<br>
<span class="badge badge-pill badge-danger">
<i class="fas fa-thumbs-up mx-2" aria-hidden="true"></i>{{ bus.liked.all.count }}</span>
</td>
<td ><span class="badge  badge-dark"><h5>Frw <text class="font-weight-bold">{{ bus.ticket_price }}</text></h5></span></td>
       

        <td><a href="{% url 'bus_detail' bus.pk bus.slug %}"><text class="text text-danger"><input class="btn btn-outline-danger float-right" type="submit" value="Book Ticket"></text></a></td>

 </tr>

    </table>
    <small class="text-primary">added {{ bus.created|timesince }} ago</small>
</p>
{% endfor %}
<p>
            {% else %}
            
                <h2>No <img src="{% static 'img/favicon.png' %}" > found.</h2> </p>
            {% endif %}

<div class="row justify-content-center border bg-light">
         <div class="pagination">
    <span class="step-links">
        {% if buses.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ buss.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            <small class="text-info">Page {{ buses.number }} of {{ buses.paginator.num_pages }}.</small>
        </span>

        {% if buses.has_next %}
            <a href="?page={{ buss.next_page_number }}">next</a>
            <a href="?page={{ buss.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>

{% endblock %}